# Generated by Django 4.1.3 on 2022-11-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='event',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
