# Generated by Django 4.1.3 on 2022-11-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_preview_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='project_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
