# Generated by Django 4.1.3 on 2022-11-18 21:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_event_end_date_event_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='avatar.png', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 300], upload_to=''),
        ),
    ]
